=== kdidenko/ito-mvc/ito-mvc/html/com/ito-global/schema/mvc/actions-mapping-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.ito-global.com/schema/mvc"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ito-global.com/schema/mvc">

	<!-- element <target> tag -->
	<xsd:element name="target">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:string" />
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="location" type="xsd:anyURI" use="required" />
			<xsd:attribute name="condition" use="optional">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="onsuccess" />
						<xsd:enumeration value="onfailure" />
						<xsd:enumeration value="onabort" />
					</xsd:restriction>		
				</xsd:simpleType>
			</xsd:attribute>			
		</xsd:complexType>	
	</xsd:element>

	<!-- element <forwards> tag -->
	<xsd:element name="forwards">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="target" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<!-- element <property> tag -->
	<xsd:element name="property">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" />
			<xsd:attribute name="value" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<!-- element <controller> tag -->
	<xsd:element name="controller">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="class" type="xsd:string"
				default="com.ito.mvc.defaults.BaseActionControllerImpl" />
			<xsd:attribute name="method" type="xsd:string" default="handleActionRequest" />
		</xsd:complexType>
	</xsd:element>

	<!-- element <template> tag -->
	<xsd:element name="template">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" />
			<xsd:attribute name="path" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<!-- element <action> tag -->
	<xsd:element name="action">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="controller" maxOccurs="1" minOccurs="0" />
				<xsd:element ref="template" maxOccurs="1" minOccurs="0" />
				<xsd:element ref="property" maxOccurs="unbounded" minOccurs="0"/>
				<xsd:element ref="forwards" maxOccurs="1" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="id" type="xsd:string" use="optional" />
		</xsd:complexType>
	</xsd:element>

	<!-- Top-level <actions> tag -->
	<xsd:element name="actions">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="action" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== kdidenko/ito-mvc/branches/ito-global/html/actions-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="http://www.ito-global.com/schema/mvc" 
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.ito-global.com/schema/mvc com/ito-global/schema/mvc/actions-mapping-1.0.xsd  
		 					 http://www.ito-global.com/schema/mvc http://www.ito-global.com/schema/mvc/actions-mapping-1.0.xsd" >

	<action name="/index.html" id="home">
		<controller class="com.ito-global.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/index.html" />
		<!-- forwards id="navigation">
			<target name="Start" location="/start-operating.html" />
			<target name="Help" location="/help-start-operating.html" />
			<target name="Cancel" location="/index.html" id="navCncl" />
		</forwards-->
	</action>
	
	<action name="/login.html" id="home">
		<controller class="com.ito-global.users.AuthenticationController" 
			method="login" />
		<template name="home.html" path="templates/home.html"/>
		<forwards>
			<target location="registration.html" name="registration" condition="onfailure"/>		
		</forwards>
	</action>	
	
	
	<action name="/registration.html" id="home">
		<controller class="com.ito-global.mvc.defaults.BaseActionControllerImpl" />
		<template name="registration.html" path="templates/registration.html" />
	</action>
	
	<action name="/registr.html" id="home">
		<controller class="com.ito-global.users.RegistrationController" 
			method="registration"/>
		<template name="home.html" path="templates/home.html" />
		<forwards>
			<target location="registration.html" name="registration" condition="onfailure"/>		
		</forwards>
	</action>
	
</actions>

=== kdidenko/ito-mvc/html/actions-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="http://www.ito-global.com/schema/mvc" 
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.ito-global.com/schema/mvc com/ito-global/schema/mvc/actions-mapping-1.0.xsd  
		 					 http://www.ito-global.com/schema/mvc http://www.ito-global.com/schema/mvc/actions-mapping-1.0.xsd" >

	<action name="/index.html" id="home">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />
		<!-- forwards id="navigation">
			<target name="Start" location="/start-operating.html" />
			<target name="Help" location="/help-start-operating.html" />
			<target name="Cancel" location="/index.html" id="navCncl" />
		</forwards-->
	</action>

	<action name="/schools.html" id="schools">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>

	<action name="/trainings.html" id="trainings">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>

	<action name="/community.html" id="community">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>	

	<action name="/discussions.html" id="discussions">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>	

	<action name="/help.html" id="help">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>

	<action name="/about.html" id="about">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>	
	
	<action name="/overview.html" id="home">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>
	
	<action name="/my-responses.html" id="my-responses">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>
	
	<action name="/valuate-responses.html" id="valuate-responses">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>
	
	<action name="/my-challenges.html" id="my-challenges">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>
	
	<action name="/messages.html" id="messages">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>


	<action name="/login.html" id="login">
		<controller class="com.itoglobal.users.AuthenticationController" 
			method="login" />
		<forwards>
			<target location="/index.html" name="home" condition="onsuccess"/>
			<target location="/login-failed.html" name="login-failed" condition="onfailure"/>		
		</forwards>
	</action>
	
	<action name="/signout.html" id="signout">
		<controller class="com.itoglobal.users.AuthenticationController" 
			method="logout" />
		<forwards>
			<target location="/index.html" name="home" condition="onsuccess"/>
		</forwards>
	</action>
	
	<action name="/login-form.html" id="login-form">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/views/sidebars/login-form.html"/>
	</action>	

	<action name="/login-failed.html" id="login-failed">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-one-column.html"/>
	</action>
	
	<action name="/reset-password.html" id="reset-password">
		<controller class="com.itoglobal.users.RegistrationController" method="resetPassword"/>
		<template name="index.html" path="templates/layout-one-column.html"/>
		<forwards>
			<target location="/check-email.html" name="check-email" condition="onsuccess"/>		
		</forwards>
		<property name="template" value="templates/plain/reset-password.txt"/>
	</action>
	
	<action name="/new-password.html" id="new-password">
		<controller class="com.itoglobal.users.RegistrationController" method="resetPassword"/>
		<template name="index.html" path="templates/layout-one-column.html"/>
		<forwards>
			<target location="/login-failed.html" name="login-failed" condition="onsuccess"/>
			<target location="/reset-password.html" name="reset-password" condition="onfailure"/>		
		</forwards>
	</action>
	
	<action name="/check-email.html" id="check-email">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-one-column.html"/>
	</action>
	
	<action name="/registration.html" id="registration">
		<controller class="com.itoglobal.users.RegistrationController" method="registration"/>
		<template name="index.html" path="templates/layout-one-column.html" />	
		<forwards>
			<target location="registration.html" name="registration" condition="onfailure"/>
			<target location="validation.html" name="validation" condition="onsuccess"/>
		</forwards>
		<property name="template" value="templates/plain/email-confirmation.txt"/>
	</action>

	<action name="/validation.html" id="validation">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-one-column.html" />	
	</action>
	
	<action name="/confirm-registration.html" id="login-failed">
		<controller class="com.itoglobal.users.RegistrationController" method="registration"/>
		<template name="index.html" path="templates/layout-one-column.html" />
	</action>	

	<action name="/scope.html" id="scope">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-one-column.html" />	
	</action>

	<action name="/scope-create.html" id="scope-create">
		<controller class="com.itoglobal.scopes.ScopeController" 
			method="createScope"/>
		<template name="scope.html" path="templates/scope.html" />	
	</action>

	<action name="/scope-delete.html" id="scope-delete">
		<controller class="com.itoglobal.scopes.ScopeController" 
			method="deleteScope"/>
		<template name="scope.html" path="templates/scope.html" />	
	</action>
	
	<!-- Sidebar views mapping begin -->
	<action name="/sidebar-*.html" id="sidebar">
		<controller class="com.itoglobal.lcms.controllers.SidebarController" />
		<template name="$1.html" path="templates/views/sidebars/$1.html" />
		<forwards>
			<target location="/login-form.html" name="Login" condition="onsignedoff"/>
		</forwards>
	</action>	
	<!-- Sidebar views mapping end -->	
	
	<!-- Content views mapping begin -->
	<action name="/content-*.html" id="content">
		<controller class="com.itoglobal.lcms.controllers.ContentController" />
		<template name="$1.html" path="templates/views/content/$1.html" />
		<forwards>
			<target location="/home-$1.html" name="home-$1.html" condition="onsignedoff"/>
		</forwards>
	</action>	
	<!-- Content views mapping end -->	
	
	<action name="/home-home.html" id="home-home">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/views/content/home-content.html"/>
	</action>
	<action name="/home-schools.html" id="home-schools">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/views/content/home-schools.html"/>
	</action>
	<action name="/home-trainings.html" id="home-trainings">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/views/content/home-trainings.html"/>
	</action>
	<action name="/home-community.html" id="home-community">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/views/content/community.html"/>
	</action>
	<action name="/home-discussions.html" id="home-discussions">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/views/content/discussions.html"/>
	</action>
	<action name="/home-about.html" id="home-about">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/views/content/about.html"/>
	</action>
	
	
</actions>

=== kdidenko/ito-mvc/ito-mvc/html/config-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="http://www.ito-global.com/schema/mvc" 
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.ito-global.com/schema/mvc com/ito-global/schema/mvc/actions-mapping-1.0.xsd  
		 					 http://www.ito-global.com/schema/mvc http://www.ito-global.com/schema/mvc/actions-mapping-1.0.xsd" >

	<action name="/index.html" id="home">
		<controller class="com.ito-global.mvc.defaults.BaseActionControllerImpl" />
		<template name="home" path="templates/system/html/index.html" />
	</action>
	
	<action name="/actions-list.html" id="actions-list">
		<controller class="com.ito-global.mvc.defaults.BaseActionControllerImpl" />
		<template name="actions" path="templates/system/xsl/actions-mapping.xsl" type="XSLT">
			<input name="data" value="actions-mapping.xml" type="FILE" />
		</template>
	</action>
	
</actions>

=== kdidenko/ito-mvc/branches/ito-nlp/html/actions-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns="http://www.ito-global.com/schema/mvc" 
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.ito-global.com/schema/mvc com/ito-global/schema/mvc/actions-mapping-1.0.xsd  
		 					 http://www.ito-global.com/schema/mvc http://www.ito-global.com/schema/mvc/actions-mapping-1.0.xsd" >

	<action name="/index.html" id="home">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />
		<!-- forwards id="navigation">
			<target name="Start" location="/start-operating.html" />
			<target name="Help" location="/help-start-operating.html" />
			<target name="Cancel" location="/index.html" id="navCncl" />
		</forwards-->
	</action>
	
	<action name="/schools.html" id="schools-browse">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>
	
	<action name="/trainings.html" id="trainings-browse">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>
	
	<action name="/community.html" id="community">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>	
	
	<action name="/discussions.html" id="discussions">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>	
	
	<action name="/help.html" id="help">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>
	
	<action name="/about.html" id="about">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-two-columns.html" />	
	</action>	
	
	<action name="/login.html" id="login">
		<controller class="com.itoglobal.users.AuthenticationController" 
			method="login" />
		<template name="index.html" path="templates/layout-two-columns.html"/>
		<forwards>
			<target location="registration.html" name="registration" condition="onfailure"/>		
		</forwards>
	</action>
	
	<action name="/registration.html" id="registration">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="index.html" path="templates/layout-one-column.html" />	
	</action>
	
	<action name="/scoupe.html" id="scoupe">
		<controller class="com.itoglobal.mvc.defaults.BaseActionControllerImpl" />
		<template name="scoupe.html" path="templates/scoupe.html" />	
	</action>
	
	<action name="/scoupe_create.html" id="scoupe">
		<controller class="com.itoglobal.services.ContextService" 
			method="createContext"/>
		<template name="scoupe.html" path="templates/scoupe.html" />	
		<forwards>
			<target location="/home.html" name="scoupe" condition="onfailure"/>		
		</forwards>
	</action>
	
	<action name="/scoupe_delete.html" id="scoupe">
		<controller class="com.itoglobal.services.ContextService" 
			method="deleteContext"/>
		<template name="scoupe.html" path="templates/scoupe.html" />	
		<forwards>
			<target location="/home.html" name="scoupe" condition="onfailure"/>		
		</forwards>
	</action>
</actions>
